Registration Page
andrianarivo/recipe_app pull request #15
Opened 2023-09-05 19:05 UTC by andrianarivo

Registration page:

- [x] Should be built with Devise.

2023-09-05 22:44 UTC, rachaouldbabaali requested changes
Hi @andrianarivo , 

Good job so far!
There are some issues that you still need to work on to go to the next task but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


 Happy coding!👏👏👏


------

2023-09-05 22:45 UTC, rachaouldbabaali commented on app/views/devise/registrations/new.html.erb
> +    </div>
Add "Name" Field to Registration Page: Currently, the registration page appears to lack a "Name" field. Including a "Name" field during user registration can provide a more personalized experience and improve user profiling. Ensure that this field is appropriately validated and stored in your user database.

2023-09-05 23:14 UTC, rachaouldbabaali commented
![image](https://github.com/andrianarivo/recipe_app/assets/33148222/68c488f9-f82c-42ef-b551-90a828783819)
edit recipe is not working well

2023-09-06 07:44 UTC, andrianarivo commented
Thank you for your thorough review @rachaouldbabaali ! I'll make the changes and notify you soon

2023-09-06 08:46 UTC, rachaouldbabaali approved these changes
Hi @andrianarivo,

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your milestone is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good commit messages
✅ Good descriptive PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

 Happy coding!👏👏👏

2023-09-06 09:23 UTC, merged